// DO NOT EDIT — auto-generated by npm run gen:recordings
import { test, expect } from '@playwright/test';

test('Example Login Flow', async ({ page }) => {
  await test.step('step 0: setViewport', async () => {
    await page.setViewportSize({ width: 1280, height: 720 });
  });

  await test.step('step 1: navigate', async () => {
    await page.goto('https://example.com/login');
    try { await page.waitForLoadState('domcontentloaded'); } catch { /* timeout OK */ }
  });

  await test.step('step 2: click', async () => {
    const locator = page.getByRole('textbox', { name: 'Email' });
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 3: change', async () => {
    const locator = page.getByRole('textbox', { name: 'Email' });
    await expect(locator).toBeVisible();
    await locator.fill('user@example.com');
  });

  await test.step('step 4: click', async () => {
    const locator = page.getByRole('textbox', { name: 'Password' });
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 5: change', async () => {
    const locator = page.getByRole('textbox', { name: 'Password' });
    await expect(locator).toBeVisible();
    await locator.fill('secretpass123');
  });

  await test.step('step 6: click', async () => {
    const locator = page.getByRole('button', { name: 'Sign in' });
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 7: hover', async () => {
    const locator = page.getByRole('button', { name: 'User Menu' });
    await expect(locator).toBeVisible();
    await locator.hover();
  });

  await test.step('step 8: keyDown', async () => {
    await page.keyboard.down('Escape');
  });

  await test.step('step 9: keyUp', async () => {
    await page.keyboard.up('Escape');
  });

  await test.step('step 10: scroll', async () => {
    await page.mouse.wheel(0, 300);
  });

  await test.step('step 11: customStep', async () => {
    // Custom step: verify dashboard loaded
  });

});
