// DO NOT EDIT — auto-generated by npm run gen:recordings
import { test, expect } from '@playwright/test';

test('QAC_Login', async ({ page }) => {
  await test.step('step 0: setViewport', async () => {
    await page.setViewportSize({ width: 1365, height: 945 });
  });

  await test.step('step 1: navigate', async () => {
    await page.goto('https://appuat.qaconnector.com/ARP/login');
    try { await page.waitForLoadState('domcontentloaded'); } catch { /* timeout OK */ }
  });

  await test.step('step 2: click', async () => {
    const locator = page.locator('#\\:r1\\:');
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 3: change', async () => {
    const locator = page.locator('#\\:r1\\:');
    await expect(locator).toBeVisible();
    await locator.fill('rtarvids@celticqa.com');
  });

  await test.step('step 4: keyDown', async () => {
    await page.keyboard.down('Alt');
  });

  await test.step('step 5: click', async () => {
    const locator = page.locator('#\\:r0\\: > div:nth-of-type(2) input');
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 6: change', async () => {
    const locator = page.locator('#\\:r0\\: > div:nth-of-type(2) input');
    await expect(locator).toBeVisible();
    await locator.fill('C3lt!c123');
  });

  await test.step('step 7: click', async () => {
    const locator = page.getByRole('button', { name: 'Login', exact: true });
    await expect(locator).toBeVisible();
    await locator.click();
  });

  await test.step('step 8: waitForElement', async () => {
    await expect(page.locator('span.customHeader_text__qswws')).toBeVisible();
  });

});
